// <auto-generated />
namespace MyMovies.Entities.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelatedMovies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelatedMovies));
        
        string IMigrationMetadata.Id
        {
            get { return "201701030035121_RelatedMovies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
